# Generated by Django 5.1.1 on 2024-09-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/defualt.jpeg', upload_to='profile_pics'),
        ),
    ]
